### PR TITLE
Create a mount script instead of editing /etc/fstab

### PR DESCRIPTION
**Pull request by jandubois**
This enables support for mount points that include spaces. `/etc/fstab` normally supports encoding special characters in filenames using octal constants (like "\040` for a space), but that doesn't work on Alpine.

Signed-off-by: Jan Dubois <jan.dubois@suse.com>
(cherry picked from commit eb3d0b78d88db15c365e8f80b4be66b1cb302f3d)

This is a cherry-pick of https://github.com/rancher-sandbox/alpine-lima/pull/15 that should have been made to the upstream repo first.

Discovered in https://github.com/lima-vm/lima/issues/2235#issuecomment-1986374216.

Relevant to https://github.com/lima-vm/lima/pull/2234

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
What should we do with `/etc/fstab` in an existing data disk?

**Comment by jandubois** [comment]
> What should we do with `/etc/fstab` in an existing data disk?

Just leave it as is?

It either works for the user because they don't have mount points with spaces in them (most likely), or it never did, in which case they would have to create a new instance to get this new functionality.

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Comment by AkihiroSuda** [comment]
Do you plan to make a new release with this?

**Comment by AkihiroSuda** [comment]
Shall I make a new release by myself?

**Comment by jandubois** [comment]
> Shall I make a new release by myself?

I can make a release, but I thought you wanted me to update the `awk` script so it doesn't require the empty line?

**Comment by AkihiroSuda** [comment]
> > Shall I make a new release by myself?
> 
> I can make a release, but I thought you wanted me to update the `awk` script so it doesn't require the empty line?

Thanks, yes, updating awk is nice, but not a hard blocker.

**Pull request merged**
