### PR TITLE
Refactor: rename nerdctl to nerdctl-full

### PR DESCRIPTION
**Pull request by afbjorklund**
Since the bundle package also contains other software.

These are also available as regular Alpine packages.

### CODE REVIEW

**Comment by afbjorklund** [comment]
@jandubois : broke this out from the "nerdctl" edition

**Comment by AkihiroSuda** [comment]
I'm not sure about this.
I'd say "nerdctl-full" refers to the upstream nerdctl-full distribution ( https://github.com/containerd/nerdctl/releases/download/v1.4.0/nerdctl-full-1.4.0-linux-amd64.tar.gz )

**Comment by afbjorklund** [comment]
Currently we download "nerdctl-full", and rename it to "nerdctl"

```Makefile
nerdctl-$(NERDCTL_VERSION)-$(ARCH):
        curl -o $@ -Ls https://github.com/containerd/nerdctl/releases/download/v$(NERDCTL_VERSION)/nerdctl-full-$(NERDCTL_VERSION)-linux-$(ARCH_ALIAS).tar.gz
```

**Review by jandubois — APPROVED** [review]
Thanks, LGTM

**Comment by jandubois** [comment]
I've merged this change because it makes sense to normalize the name.

It feels a bit pointless though, as `rd` is the only edition that uses it, and it is no longer built out of this repo, but from https://github.com/rancher-sandbox/alpine-lima.

And then we have #77 about letting Lima bundle nerdctl, just like for all other images.

Anyways, I've been wondering if I should remove the `rd` specific config options from this repo and maintain them purely in the downstream fork. What do you think @AkihiroSuda ?

**Comment by AkihiroSuda** [comment]
> rd

SGTM

**Pull request merged**
