### PR TITLE
cloud-init case doesn't work correctly 

### PR DESCRIPTION
**Pull request by sporynin**
e2fsprogs is needed for mkfs.ext4 in boot/05-persistent-data-volume.sh

### CODE REVIEW

**Comment by jandubois** [comment]
You also need to add it to `mkimg.lima.sh` as well.

**Comment by jandubois** [comment]
Also please add a DCO signature to your commits as per https://github.com/lima-vm/alpine-lima/pull/39/checks?check_run_id=4725578866

**Comment by sporynin** [comment]
> Also please add a DCO signature to your commits as per https://github.com/lima-vm/alpine-lima/pull/39/checks?check_run_id=4725578866

done

**Comment by sporynin** [comment]
> You also need to add it to `mkimg.lima.sh` as well.

I have double checked and don't think so, but sudo is needed in apkvol.

**Comment by jandubois** [comment]
I've checked the `ci` edition ISO, and it already includes both `e2fsprogs` and `sudo` packages. I don't understand why you think they need to be added; please give an example of what is failing, and how!

**Comment by jandubois** [comment]
```console
$ limactl shell ci
lima-ci:~$ sudo apk list | grep e2fsprogs
e2fsprogs-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT) [installed]
libcom_err-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT) [installed]
e2fsprogs-static-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT)
e2fsprogs-libs-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT) [installed]
e2fsprogs-extra-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT) [installed]
e2fsprogs-dev-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT)
e2fsprogs-doc-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT)
```

**Comment by sporynin** [comment]
> ```
> $ limactl shell ci
> lima-ci:~$ sudo apk list | grep e2fsprogs
> e2fsprogs-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT) [installed]
> libcom_err-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT) [installed]
> e2fsprogs-static-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT)
> e2fsprogs-libs-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT) [installed]
> e2fsprogs-extra-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT) [installed]
> e2fsprogs-dev-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT)
> e2fsprogs-doc-1.46.2-r0 x86_64 {e2fsprogs} (GPL-2.0-or-later AND LGPL-2.0-or-later AND BSD-3-Clause AND MIT)
> ```

make lima ALPINE_VERSION=3.15.0 ARCH=aarch64 EDITION=k3s
ALPINE_VERSION=3.15.0 EDITION=k3s ARCH=aarch64 ./lima.sh
INFO[0000] Sending SIGKILL to the QEMU process 80044    
INFO[0000] Sending SIGKILL to the host agent process 80037 
INFO[0000] Removing *.pid *.sock under "/Users/yuran/.lima/k3s" 
INFO[0000] Removing "/Users/yuran/.lima/k3s/ga.sock"    
INFO[0000] Removing "/Users/yuran/.lima/k3s/ha.pid"     
INFO[0000] Removing "/Users/yuran/.lima/k3s/ha.sock"    
INFO[0000] Removing "/Users/yuran/.lima/k3s/qemu.pid"   
INFO[0000] Removing "/Users/yuran/.lima/k3s/qmp.sock"   
INFO[0000] Removing "/Users/yuran/.lima/k3s/serial.sock" 
INFO[0000] Removing "/Users/yuran/.lima/k3s/ssh.sock"   
INFO[0000] Deleted "k3s" ("/Users/yuran/.lima/k3s")     
INFO[0000] Terminal is not available, proceeding without opening an editor 
INFO[0000] Attempting to download the image from "/Users/yuran/Projects/my-alpine-lima/iso/alpine-lima-k3s-3.15.0-aarch64.iso"  digest=
INFO[0000] Downloaded image from "/Users/yuran/Projects/my-alpine-lima/iso/alpine-lima-k3s-3.15.0-aarch64.iso" 
WARN[0001] [hostagent] field `firmware.legacyBIOS` is not supported for architecture "aarch64", ignoring 
INFO[0001] [hostagent] Starting QEMU (hint: to watch the boot progress, see "/Users/yuran/.lima/k3s/serial.log") 
INFO[0001] SSH Local Port: 40022                        
INFO[0001] [hostagent] Waiting for the essential requirement 1 of 5: "ssh" 
INFO[0020] [hostagent] The essential requirement 1 of 5 is satisfied 
INFO[0020] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0060] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0100] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0140] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0180] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0220] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0260] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0300] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh" 
INFO[0340] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"

**Comment by sporynin** [comment]
The same result for EDITION=ci

At moment of
 INFO[0340] [hostagent] Waiting for the essential requirement 2 of 5: "user session is ready for ssh"
 
Inside VM we have: 

 1328 root      0:00 [ipv6_addrconf]
 1626 root      0:00 /sbin/syslogd -t
 1762 root      0:00 /sbin/udhcpc -b -R -p /var/run/udhcpc.eth0.pid -i eth0 -x hostname:lima-ci
 2150 root      0:00 /sbin/acpid
 2196 root      0:00 sshd.pam: /usr/sbin/sshd.pam [listener] 0 of 10-100 startups
 2368 root      0:00 supervise-daemon lima-guestagent --start --pidfile /run/lima-guestagent.pid /usr/local/bin/lima-guestagent -- daemon
 2370 root      0:00 /usr/local/bin/lima-guestagent daemon
 2607 root      0:00 /sbin/getty 38400 tty1
 2608 root      0:00 /sbin/getty 38400 tty2
 2609 root      0:00 /sbin/getty 38400 tty3
 2611 root      0:00 /sbin/getty 38400 tty4
 2612 root      0:00 /sbin/getty 38400 tty5
 2613 root      0:00 /sbin/getty 38400 tty6
 2614 root      0:00 /sbin/getty -L 0 ttyAMA0 vt100
 2619 root      0:00 sshd.pam: yuran [priv]
 2621 yuran     0:00 sshd.pam: yuran@pts/0
 2641 yuran     0:00 /bin/ash
 **2642 yuran     0:00 /bin/ash -c until sudo diff -q /run/lima-ssh-ready /mnt/lima-cidata/meta-data 2>/dev/null; do sleep 3; done
 2644 yuran     0:00 timeout 30s bash -c until sudo diff -q /run/lima-ssh-ready /mnt/lima-cidata/meta-data 2>/dev/null; do sleep 3; done**

lima-ci:~# df -h
Filesystem                Size      Used Available Use% Mounted on
devtmpfs                 10.0M         0     10.0M   0% /dev
shm                       1.9G         0      1.9G   0% /dev/shm
/dev/vda                 73.9M     73.9M         0 100% /media/vda
tmpfs                     1.9G     98.8M      1.8G   5% /
tmpfs                   784.2M    304.0K    783.9M   0% /run
/dev/loop0               15.8M     15.8M         0 100% /.modloop
/dev/disk/by-label/cidata
                          6.6M      6.6M         0 100% /mnt/lima-cidata
cgroup_root              10.0M         0     10.0M   0% /sys/fs/cgroup
lima-ci:~# lsblk 
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
loop0    7:0    0 15.7M  1 loop /.modloop
vda    253:0    0 73.9M  1 disk /media/vda
├─vda1 253:1    0  130K  1 part 
├─vda2 253:2    0  1.4M  1 part 
└─vda3 253:3    0 72.3M  1 part 
vdb    253:16   0  100G  0 disk 
└─vdb1 253:17   0  100G  0 part 
vdc    253:32   0  6.6M  1 disk /mnt/lima-cidata

lima-ci:/var/log# grep mkfs *
cloud-init-output.log:+ mkfs.ext4 -L data-volume /dev/vdb1
cloud-init-output.log:/mnt/lima-cidata/boot/05-persistent-data-volume.sh: line 34: mkfs.ext4: not found

**Comment by jandubois** [comment]
> make lima ALPINE_VERSION=3.15.0 ARCH=aarch64 EDITION=k3s

Thank you! I was testing with Alpine 3.14, and it is only required by Alpine 3.15+ because these 2 packages are no longer required by `cloud-init`:

* https://github.com/alpinelinux/aports/commit/9d2f65930162d4f60251cdd245a6276caaea2a0f#diff-8ae97973c70f244675ab1bf56750b126d1200afcc83c1807c3a32cec772fd4bb removed `e2fsprogs-extra`
* https://github.com/alpinelinux/aports/commit/9dd8546697ad684d400beafa5dd65e01542b629a#diff-8ae97973c70f244675ab1bf56750b126d1200afcc83c1807c3a32cec772fd4bb replaced `sudo` with `doas`

**Comment by jandubois** [comment]
> > You also need to add it to `mkimg.lima.sh` as well.
> 
> I have double checked and don't think so, but sudo is needed in apkvol.

Looks like `e2fsprogs` is always included on the ISO, so it is indeed not necessary.

`sudo` however is not on the iso, so the image will only work if the host has an active Internet connection. I guess this is fine, given that the `ci` edition is not supposed to work offline anyways (e.g. it intentionally doesn't bundle `sshfs`, so it can be used for testing that Lima will pull those down).

I'll probably still add a comment about this later, just in case I start wondering about it again in 3 months. 😄

**Review by jandubois — APPROVED** [review]

**Pull request merged**
